[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
axum = { version = "0.8.1", features = ["macros"] }
ethercrab = "0.5.2"
env_logger = "0.11.6"
log = "0.4.25"
signal-hook = "0.3.17"
network-interface = "2.0.0"
serde_json = "1.0.137"
anyhow = "1.0.95"
