[package]
name = "server"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"


[dependencies]

# ethercat
ethercrab = "0.6"
ethercat_hal = { path = "../ethercat-hal" }
control_core = { path = "../control-core" }

# concurrency
thread-priority = "1.2.0"
futures = "0.3.31"

# web
socketioxide = "0.16.0"
tower-http = { version = "0.6.2", features = ["cors", "trace", "fs"] }
axum = { version = "0.8.1", features = ["macros"] }

# utility
uom = "0.36.0"
chrono = "0.4.39"
serde = "1.0.217"
anyhow = "1.0.95"
serde_json = "1.0.137"
log = "0.4.25"
env_logger = "0.11.6"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
open = "5.3.2"
bitvec = "1.0.1"
lazy_static = "1.5.0"
smol = "2.0.2"

[dev-dependencies]
approx = "0.5.1"
