[package]
name = "ethercat_hal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ethercrab = "0.6"
ethercat_hal_derive = { version = "0.1.0", path = "../ethercat-hal-derive" }
bitvec = { version = "1.0.1", features = ["alloc"] }
smol = "2.0.2"
