name: Rust

on:
  push:
    branches: ["master", "bugfix/22"]
  pull_request:
    branches: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set Rust version
        run: rustup override set 1.86
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
